### PR TITLE
Improvements for iOS scroll & new precommit rules.

### PR DESCRIPTION
**Pull request by kikoruiz**
### Summary
* Added new precommit rules.
* Removed unnecessary state properties.
* Really really improved scroll event for iOS devices by:
  * Disabling general events in header layer.
  * Avoiding overscroll on content layer (bottom and top).
* Larger padding on close button.
* Some small fixes.

Big thanks to @miduga and please review @SUI-Components/developers.

### CODE REVIEW

**Comment by FranDelaCasa** [comment]
👍  Grandes!!!

**Comment by miduga** [comment]
Pa' lamerlo 👍

**Comment by aleanez** [comment]
:+1:

**Comment by ruben-martin-lozano** [comment]
👍

**Pull request merged**
